In [8]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("http://51.91.120.89/extras/diabetes.csv")
df

pregnancies  glucose  bloodpressure  skinthickness  insulin   bmi  \
0               6    148.0           72.0           35.0      0.0  33.6   
1               1     85.0           66.0           29.0      0.0  26.6   
2               8    183.0           64.0            0.0      0.0  23.3   
3               1     89.0           66.0           23.0     94.0  28.1   
4               0    137.0           40.0           35.0    168.0  43.1   
...           ...      ...            ...            ...      ...   ...   
1531           10    101.0           76.0           48.0    180.0  32.9   
1532            2    122.0           70.0           27.0      0.0  36.8   
1533            5    121.0           72.0           23.0    112.0  26.2   
1534            1    126.0           60.0            0.0      0.0  30.1   
1535            1     93.0           70.0           31.0      0.0  30.4   

      diabetespedigreefunction   age  outcome  
0                        0.627  50.0        1  
1                        0.351  31.0        0  
2                        0.672  32.0        1  
3                        0.167  21.0        0  
4                        2.288  33.0        1  
...                        ...   ...      ...  
1531                     0.171  63.0        0  
1532                     0.340  27.0        0  
1533                     0.245  30.0        0  
1534                     0.349  47.0        1  
1535                     0.315  23.0        0  

[1536 rows x 9 columns]

In [3]:
df.describe()

pregnancies      glucose  bloodpressure  skinthickness      insulin  \
count  1536.000000  1532.000000    1530.000000    1528.000000  1530.000000   
mean      3.845052   120.763708      69.101961      20.498691    79.274510   
std       3.368480    31.894098      19.381680      15.930062   114.895763   
min       0.000000     0.000000       0.000000       0.000000     0.000000   
25%       1.000000    99.000000      62.000000       0.000000     0.000000   
50%       3.000000   117.000000      72.000000      23.000000    25.000000   
75%       6.000000   140.000000      80.000000      32.000000   126.000000   
max      17.000000   199.000000     122.000000      99.000000   846.000000   

               bmi  diabetespedigreefunction          age      outcome  
count  1532.000000               1526.000000  1534.000000  1536.000000  
mean     31.994778                  0.471843    33.230769     0.348958  
std       7.870785                  0.331776    11.760723     0.476796  
min       0.000000                  0.078000    21.000000     0.000000  
25%      27.300000                  0.243250    24.000000     0.000000  
50%      32.000000                  0.371000    29.000000     0.000000  
75%      36.600000                  0.626750    41.000000     1.000000  
max      67.100000                  2.420000    81.000000     1.000000

In [5]:
df.isna().sum()

pregnancies                  0
glucose                      4
bloodpressure                6
skinthickness                8
insulin                      6
bmi                          4
diabetespedigreefunction    10
age                          2
outcome                      0
dtype: int64

In [6]:
df.outcome.value_counts()

0    1000
1     536
Name: outcome, dtype: int64

In [9]:
for col in ['glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age']:
    df[col].replace(0, np.NaN, inplace=True)
    mean_ = df[col].mean()
    df[col].fillna(mean_, inplace=True)

In [10]:
df.describe()

pregnancies      glucose  bloodpressure  skinthickness      insulin  \
count  1536.000000  1536.000000    1536.000000    1536.000000  1536.000000   
mean      3.845052   121.557162      72.415068      29.109665   155.102302   
std       3.368480    30.314180      12.082412       8.759883    84.603816   
min       0.000000    44.000000      24.000000       7.000000    14.000000   
25%       1.000000    99.750000      64.000000      25.000000   122.000000   
50%       3.000000   117.000000      72.415068      29.109665   155.102302   
75%       6.000000   140.000000      80.000000      32.000000   155.102302   
max      17.000000   199.000000     122.000000      99.000000   846.000000   

               bmi  diabetespedigreefunction          age      outcome  
count  1536.000000               1536.000000  1536.000000  1536.000000  
mean     32.460927                  0.471843    33.230769     0.348958  
std       6.848550                  0.330694    11.753059     0.476796  
min      18.200000                  0.078000    21.000000     0.000000  
25%      27.575000                  0.244000    24.000000     0.000000  
50%      32.400000                  0.375500    29.000000     0.000000  
75%      36.525000                  0.624500    41.000000     1.000000  
max      67.100000                  2.420000    81.000000     1.000000

In [12]:
df.to_csv("cukrzyca.csv", index=False)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [18]:
X = df.iloc[ : , :-1 ]
y = df.outcome

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [20]:
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

/Users/marian/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7597402597402597

In [23]:
y_pred = model.predict(X_test)
pd.DataFrame( confusion_matrix(y_test, y_pred) )

0   1
0  178  35
1   39  56

In [25]:
X_test.iloc[[0]]

pregnancies  glucose  bloodpressure  skinthickness  insulin   bmi  \
1408            0    102.0           86.0           17.0    105.0  29.3   

      diabetespedigreefunction   age  
1408                     0.695  27.0

In [26]:
model.predict( X_test.iloc[[0]] )

array([0])

In [27]:
y_test.iloc[0]

0

In [28]:
model.predict_proba( X_test.iloc[[0]] )

array([[0.8966241, 0.1033759]])

In [29]:
model.predict( X_test.iloc[[-1]] ), model.predict_proba( X_test.iloc[[-1]] )

(array([0]), array([[0.63241763, 0.36758237]]))

In [30]:
X_test.iloc[[-1]] 

pregnancies  glucose  bloodpressure  skinthickness     insulin   bmi  \
1247            4    132.0           86.0           31.0  155.102302  28.0   

      diabetespedigreefunction   age  
1247                     0.419  63.0

In [33]:
# Balansowanie klasy wynikowej
# 500 próbek z klasy 0
# 500 próbek z klasy 1
df1 = df.query(" outcome==0 ").sample(n=500, random_state=42)
df2 = df.query(" outcome==1 ").sample(n=500, random_state=42)

In [34]:
df3 = pd.concat([df1,df2]).sample(n=1000, random_state=42)
df3

pregnancies  glucose  bloodpressure  skinthickness     insulin   bmi  \
1125           13    129.0      72.415068      30.000000  155.102302  39.9   
776             2    197.0      70.000000      45.000000  543.000000  30.5   
270            10    101.0      86.000000      37.000000  155.102302  45.6   
1387            0    119.0      72.415068      29.109665  155.102302  32.4   
1407            1    100.0      74.000000      12.000000   46.000000  19.5   
...           ...      ...            ...            ...         ...   ...   
857             1    107.0      68.000000      19.000000  155.102302  26.5   
751             1    121.0      78.000000      39.000000   74.000000  39.0   
415             3    173.0      84.000000      33.000000  474.000000  35.7   
30              5    109.0      75.000000      26.000000  155.102302  36.0   
1433            1    112.0      80.000000      45.000000  132.000000  34.8   

      diabetespedigreefunction   age  outcome  
1125                     0.569  44.0        1  
776                      0.158  53.0        1  
270                      1.136  38.0        1  
1387                     0.141  24.0        1  
1407                     0.149  28.0        0  
...                        ...   ...      ...  
857                      0.165  24.0        0  
751                      0.261  28.0        0  
415                      0.258  22.0        1  
30                       0.546  60.0        0  
1433                     0.217  24.0        0  

[1000 rows x 9 columns]

In [35]:
X = df3.iloc[ : , :-1 ]
y = df3.outcome

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

/Users/marian/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.695

In [36]:
y_pred = model.predict(X_test)
pd.DataFrame( confusion_matrix(y_test, y_pred) )

0   1
0  85  31
1  30  54